/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminloginRouteImport } from './routes/adminlogin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizzesIndexRouteImport } from './routes/quizzes.index'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as DebuggingIndexRouteImport } from './routes/debugging.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as QuizzesIdRouteImport } from './routes/quizzes.$id'
import { Route as ProblemsIdRouteImport } from './routes/problems.$id'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminQuizzesRouteImport } from './routes/admin.quizzes'
import { Route as AdminProblemsRouteImport } from './routes/admin.problems'
import { Route as AdminLeaderboardRouteImport } from './routes/admin.leaderboard'
import { Route as AdminDebuggingRouteImport } from './routes/admin.debugging'
import { Route as AdminCodingRouteImport } from './routes/admin.coding'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminloginRoute = AdminloginRouteImport.update({
  id: '/adminlogin',
  path: '/adminlogin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIndexRoute = QuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebuggingIndexRoute = DebuggingIndexRouteImport.update({
  id: '/debugging/',
  path: '/debugging/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesIdRoute = QuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIdRoute = ProblemsIdRouteImport.update({
  id: '/problems/$id',
  path: '/problems/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/admin/quizzes',
  path: '/admin/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProblemsRoute = AdminProblemsRouteImport.update({
  id: '/admin/problems',
  path: '/admin/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/admin/leaderboard',
  path: '/admin/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDebuggingRoute = AdminDebuggingRouteImport.update({
  id: '/admin/debugging',
  path: '/admin/debugging',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCodingRoute = AdminCodingRouteImport.update({
  id: '/admin/coding',
  path: '/admin/coding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/submissions': typeof SubmissionsRoute
  '/admin/coding': typeof AdminCodingRoute
  '/admin/debugging': typeof AdminDebuggingRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/debugging/': typeof DebuggingIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/submissions': typeof SubmissionsRoute
  '/admin/coding': typeof AdminCodingRoute
  '/admin/debugging': typeof AdminDebuggingRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/admin': typeof AdminIndexRoute
  '/debugging': typeof DebuggingIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/quizzes': typeof QuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminlogin': typeof AdminloginRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/submissions': typeof SubmissionsRoute
  '/admin/coding': typeof AdminCodingRoute
  '/admin/debugging': typeof AdminDebuggingRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/problems': typeof AdminProblemsRoute
  '/admin/quizzes': typeof AdminQuizzesRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/problems/$id': typeof ProblemsIdRoute
  '/quizzes/$id': typeof QuizzesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/debugging/': typeof DebuggingIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/quizzes/': typeof QuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminlogin'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/submissions'
    | '/admin/coding'
    | '/admin/debugging'
    | '/admin/leaderboard'
    | '/admin/problems'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/submissions'
    | '/problems/$id'
    | '/quizzes/$id'
    | '/admin/'
    | '/debugging/'
    | '/problems/'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adminlogin'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/submissions'
    | '/admin/coding'
    | '/admin/debugging'
    | '/admin/leaderboard'
    | '/admin/problems'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/submissions'
    | '/problems/$id'
    | '/quizzes/$id'
    | '/admin'
    | '/debugging'
    | '/problems'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/adminlogin'
    | '/dashboard'
    | '/leaderboard'
    | '/login'
    | '/register'
    | '/submissions'
    | '/admin/coding'
    | '/admin/debugging'
    | '/admin/leaderboard'
    | '/admin/problems'
    | '/admin/quizzes'
    | '/admin/students'
    | '/admin/submissions'
    | '/problems/$id'
    | '/quizzes/$id'
    | '/admin/'
    | '/debugging/'
    | '/problems/'
    | '/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminloginRoute: typeof AdminloginRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SubmissionsRoute: typeof SubmissionsRoute
  AdminCodingRoute: typeof AdminCodingRoute
  AdminDebuggingRoute: typeof AdminDebuggingRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminProblemsRoute: typeof AdminProblemsRoute
  AdminQuizzesRoute: typeof AdminQuizzesRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  ProblemsIdRoute: typeof ProblemsIdRoute
  QuizzesIdRoute: typeof QuizzesIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DebuggingIndexRoute: typeof DebuggingIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
  QuizzesIndexRoute: typeof QuizzesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminlogin': {
      id: '/adminlogin'
      path: '/adminlogin'
      fullPath: '/adminlogin'
      preLoaderRoute: typeof AdminloginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/': {
      id: '/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof QuizzesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debugging/': {
      id: '/debugging/'
      path: '/debugging'
      fullPath: '/debugging/'
      preLoaderRoute: typeof DebuggingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$id': {
      id: '/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/quizzes/$id'
      preLoaderRoute: typeof QuizzesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/problems': {
      id: '/admin/problems'
      path: '/admin/problems'
      fullPath: '/admin/problems'
      preLoaderRoute: typeof AdminProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/admin/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/debugging': {
      id: '/admin/debugging'
      path: '/admin/debugging'
      fullPath: '/admin/debugging'
      preLoaderRoute: typeof AdminDebuggingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coding': {
      id: '/admin/coding'
      path: '/admin/coding'
      fullPath: '/admin/coding'
      preLoaderRoute: typeof AdminCodingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminloginRoute: AdminloginRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SubmissionsRoute: SubmissionsRoute,
  AdminCodingRoute: AdminCodingRoute,
  AdminDebuggingRoute: AdminDebuggingRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminProblemsRoute: AdminProblemsRoute,
  AdminQuizzesRoute: AdminQuizzesRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  ProblemsIdRoute: ProblemsIdRoute,
  QuizzesIdRoute: QuizzesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DebuggingIndexRoute: DebuggingIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
  QuizzesIndexRoute: QuizzesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
